export const HTTP_ERROR_CODES = {
    BAD_REQUEST: 'BAD_REQUEST',
    UNAUTHORIZED: 'UNAUTHORIZED',
    FORBIDDEN: 'FORBIDDEN',
    NOT_FOUND: 'NOT_FOUND',
    INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
    TOO_MANY_REQUESTS: 'TOO_MANY_REQUESTS'
}
export type HTTP_ERROR_CODES = (typeof HTTP_ERROR_CODES)[keyof typeof HTTP_ERROR_CODES]
